name: openwebif

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get install automake
          sudo apt-get install git
          sudo apt-get install build-essential
          sudo apt-get install gettext
          sudo apt-get install python2-dev

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: compile python3
        run: |
          pip3 install Cheetah3
          pip3 install six
          python3 -m compileall .
          cheetah compile -R plugin

      - name: compile python2
        run: |
          sudo apt-get install -y closure-compiler nodejs npm gettext
          sudo npm install -g jshint
          pip install Cheetah
          pip install -r CI/requirements.txt
          pip install bandit==1.6.2
          pip install six
          python -m compileall .
          cheetah compile -R plugin

      - name: compile po files
        run: |
          find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
          echo done!
